### ISSUE TITLE
/usr/share/zabbix/lib/logfile_parser.rb:30:in `initialize': ArgumentError (ArgumentError)

### ISSUE THREAD

**Issue by ebalsumgo** [openshift/openshift_zabbix#10]
I am attempting to run check-user-action-log on a OSE 2.2.4, I have a /etc/openshift/openshift_zabbix.conf setup and working. To verify it is working I have check-mc-ping running and that is sending data as expected.

/usr/share/zabbix/lib/logfile_parser.rb:30:in `initialize': ArgumentError (ArgumentError)
	from ./check-user-action-log:45:in `new'
	from ./check-user-action-log:45:in `parse_action_log'
	from ./check-user-action-log:139:in `block in <main>'
	from /opt/rh/ruby193/root/usr/share/ruby/benchmark.rb:295:in `realtime'
	from ./check-user-action-log:138:in `<main>'

**Comment by kwoodson** [comment]
@ebalsumgo, 

I have lookedi nto the logfile_parser error that you are seeing.  On line 30 of the logfile_parser.rb, there is an exception that is thrown if the fname that is passed in does not exist.  It appears that it needs to be the path to the actual log file you are attempting to monitor.  Please verify this file exists.
    raise ArgumentError unless (File.exists?(fname) and File.readable?(fname))

**Comment by ebalsumgo** [comment]
Right so the log file for 2.2 is /var/log/openshift/broker/user_action.log which I already had to edit the files posted to read since by default the check-user-action-log script has a file path that doesnt exist.

root@osbroker0p:/var/log/openshift/broker:
----> ls -l user_action.log
-rw-r--r--. 1 apache apache 1905816 Mar  5 14:11 user_action.log
