### ISSUE TITLE
/usr/share/zabbix/lib/zabbix_sender.rb:35:in `initialize': undefined method `value' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by ebalsumgo** [openshift/openshift_zabbix#11]
Trying to run this on OSE 2.2.4 it fails with the above error. Trying to run it with -t -v does not produce anything different.

/usr/share/zabbix/lib/zabbix_sender.rb:35:in `initialize': undefined method `value' for nil:NilClass (NoMethodError)
	from ./check-district-capacity:46:in `new'
	from ./check-district-capacity:46:in `main'
	from ./check-district-capacity:69:in `<main>'

**Comment by kwoodson** [comment]
@ebalsumgo,
Line 35 of the constructor of the zabbix_sender class it has this.
    @fqdn          = args[:fqdn]    || Facter.fact('fqdn').value
I believe the fqdn variable either needs to be passed in when calling this class or facter would need to resolve this variable.  Please verify you are passing the fqdn into this class or that running `facter | grep fqdn` resolves from the command line.

**Comment by ebalsumgo** [comment]
root@osbroker0p:~:
----> facter | grep fqdn
fqdn => osbroker0p.*.unc.edu
root@osbroker0p:~:
---->

The FQDN is there

**Comment by kwoodson** [comment]
@ebalsumgo,

Please feel free to reach out to me, kwoodson, on #openshift on irc on freenode.  I will attempt to troubleshoot this further.

**Comment by kwoodson** [comment]
The oo-stats call stomps on the Facter.fact('fqdn').value.  Bump the zabbixsender object creation above oo-stats call.  This solution is a hack but will fix this issue.
